_target_: hypatorch.Model

defaults:
  - /submodules/image_encoder: linear

submodules_eval:


operations:
  update_encoder:
    optimizer:
      _partial_: true
      _target_: torch.optim.Adam
      lr: 0.02
  
    optimize_submodules:
      - image_encoder

    mappings:
      - image_encoder:
          inputs: 
            x: image
          outputs:
            x: logits
          calculate_grad: true
    
    losses:
        - _target_: hypatorch.HypaAssessment
          assessment:
            _target_: torch.nn.CrossEntropyLoss
            reduction: mean
          name: mean_cross_entropy
          inputs:
            input: logits
            target: class
